# Generated by Django 5.0.1 on 2024-05-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentacc', '0004_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='last_name',
        ),
    ]
