# Generated by Django 5.0.1 on 2024-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentacc', '0005_rename_first_name_studentinfo_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
